config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pics

  root 'pics#index'
end

app/models/pic.rb
class Pic
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :text, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :find_pic, only: [:show, :edit, :update, :destroy]


  def index
    @pics = Pic.all.order('created_at DESC')
  end

  def show
  end

  def new
    @pic = Pic.new
  end

  def create
    respond_to do |format|
      @pic = Pic.new(pic_params)
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully posted!' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Congrats! Pic was updated!' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully destroyed!' }
      format.json { head :no_content }
    end
  end

  private

  def pic_params
    params.require(:pic).permit(:title, :description)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Instagram
  = csrf_meta_tags
  = csp_meta_tag
  
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

%body
  - flash.each do |name, msg|
    = content_tag :div, msg, class: 'alert alert-info'
    
  = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: {multipart: true} do |f|
  - if @pic.errors.any?
    #errors
      %h2
        = pluralizze(@pic.errors.count, "error")
        prevented this pic from saving
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :title, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }
    
  = f.button :submit, input_html: { class: 'btn btn-info' }

app/views/pics/edit.html.haml
%h1 Fix Pic!

= render 'form'
= link_to "Cancel", @pic

app/views/pics/index.html.haml
- @pics.each do |pic|
  -# %h2= link_to pic.title, pic_path(pic)  -# (or)
  %h2= link_to pic.title, pic

= link_to 'Gram It', new_pic_path

app/views/pics/new.html.haml
%h1 Post Pic

= render 'form'
= link_to 'Back', pics_path

app/views/pics/show.html.haml
%h1= @pic.title
%p= @pic.description

= link_to 'Edit', edit_pic_path
= link_to 'Delete', pic_path, method: :delete, data: { confirm: "Are you sure to delete?" }
= link_to 'Back', pics_path